dataloader:
  _target_: lib.datamodules.scatterdatamodule.ScatterPatchesDataModule
  base_path:  /home/rlx/data/sar-recovery
  date_train: 20100520
  date_test:  20120720
  date_val:   20120720
  input_elems:
    - Svv
    - Svh
  output_elems:
    - Shh
  patch_size: 60
  splitmask_fn_src: "lambda h, w: data.cv_splitpixels_spatial(h, w, pixels_train = 70, pixels_test = 15, pixels_val = 15, angle = np.pi/4)"
    
model:
  _target_: lib.models.scattermodel.Scatter2Scatter
  in_channels: 2
